template: |
  # markbind-cli
  <!-- List out each of the PR for this version in the following format: -->
  <!-- #ISSUE_NUMBER ISSUE_TITLE (#PR_NUMBER) -->
  ## User Facing Changes

  ## Other Changes

  ### Miscellaneous

  <!-- Any other changes -->

  $CHANGES
tag-template: 'v$RESOLVED_VERSION'
change-template: "* $TITLE (#$NUMBER)"
category-template: "### $TITLE"
categories:
  - title: 'Documentation'
    label: 'a-Documentation 📝'
  - title: 'Code Quality'
    labels:
      - 'a-CodeQuality'
      - 'bugfix'
      - 'bug'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
name-template: v$RESOLVED_VERSION