template: |
  # markbind-cli
  <!-- List out each of the PR for this version in the following format: -->
  <!-- #ISSUE_NUMBER ISSUE_TITLE (#PR_NUMBER) -->
  ## User Facing Changes

  ## Other Changes

  <!-- Move the items below into the respective categories -->
  <!-- Then move the categories into the right headings -->

  $CHANGES
tag-template: 'v$RESOLVED_VERSION'
change-template: "* $TITLE (#$NUMBER)"
category-template: "### $TITLE"
categories:
  - title: 'Breaking changes'
  - title: 'Features'
  - title: 'Enhancements'
  - title: 'Fixes'
  - title: 'Documentation'
    label: 'a-Documentation 📝'
  - title: 'Code Quality'
    labels:
      - 'a-CodeQuality'
  - title: 'DevOps Changes'
  - title: 'Dependencies'
  - title: 'Miscellaneous'
version-resolver:
  major:
    labels:
      - 'r.major'
  minor:
    labels:
      - 'r.minor'
  patch:
    labels:
      - 'r.patch'
  default: patch
name-template: v$RESOLVED_VERSION